pwr_cnsmp <-read.table("household_power_consumption.txt", sep=";", header=TRUE)
pwr_cnsmp$Date <- as.Date(pwr_cnsmp$Date, "%d/%m/%Y")
pwr_cnsmp$time <- paste(pwr_cnsmp$Date, pwr_cnsmp$Time)
pwr_cnsmp$time <- strptime(pwr_cnsmp$time, "%Y-%m-%d %H:%M:%S")
pwr_cnsmp_fltr <- pwr_cnsmp[pwr_cnsmp$Date == "2007-2-2"|pwr_cnsmp$Date == "2007-2-1",]
#pwr_cnsmp_fltr$Global_active_power <- as.numeric(as.character(pwr_cnsmp_fltr$Global_active_power))
pwr_cnsmp_fltr$Sub_metering_1 <- as.numeric(as.character(pwr_cnsmp_fltr$Sub_metering_1))
pwr_cnsmp_fltr$Sub_metering_2 <- as.numeric(as.character(pwr_cnsmp_fltr$Sub_metering_2))
pwr_cnsmp_fltr$Sub_metering_3 <- as.numeric(as.character(pwr_cnsmp_fltr$Sub_metering_3))
png(filename = "Plot3.png")
with(pwr_cnsmp_fltr, plot(time, Sub_metering_1,type="n",ylab = "Energy sub metering",xlab =""))
with(pwr_cnsmp_fltr,lines(time,Sub_metering_1,col="gray"))
with(pwr_cnsmp_fltr,lines(time,Sub_metering_2,col="red"))
with(pwr_cnsmp_fltr,lines(time,Sub_metering_3,col="blue"))
legend("topright", lty =1,  col= c("gray", "red", "blue"), legend = c("Sub_Metering_1","Sub_Metering_2","Sub_Metering_3"))
dev.off()